_wandb:
    value:
        cli_version: 0.26.0
        e:
            1q7nc76po4xca1dn1m2bm0ajkz4mmveu:
                apple:
                    ecpuCores: 2
                    gpuCores: 32
                    macModel: MacBookPro18,2
                    memoryGb: 32
                    name: Apple M1 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "1073741824"
                codePath: scripts/simulate_sota_run.py
                codePathLocal: scripts/simulate_sota_run.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "702851526656"
                email: f.van-laarhoven2@newcastle.ac.uk
                executable: /opt/homebrew/opt/python@3.14/bin/python3.14
                git:
                    commit: 53a2f72d81ab097e791a3627c53efa97936c9333
                    remote: https://github.com/FrankAsanteVanLaarhoven/MEMDEVOS-X.git
                host: FRANKs-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-26.3.1-arm64-arm-64bit-Mach-O
                program: /Users/favl/Downloads/infraconnectAI/scripts/simulate_sota_run.py
                python: CPython 3.14.3
                root: /Users/favl/Downloads/infraconnectAI
                startedAt: "2026-04-16T01:56:27.940506Z"
                writerId: 1q7nc76po4xca1dn1m2bm0ajkz4mmveu
        m: []
        python_version: 3.14.3
        t:
            "3":
                - 2
                - 13
                - 61
            "4": 3.14.3
            "5": 0.26.0
            "12": 0.26.0
            "13": darwin-arm64
